/* ==========================================================================
   Per-module permissions chosen by the firm Admin.
   1. The role enum narrows to admin / staff / cashier. "owner" becomes
      "admin" and "accountant" becomes "staff", so nobody silently loses the
      ability to sign in; an Admin then widens or narrows what Staff and
      Cashier can do from Roles & Permissions.
   2. Access to the practice modules (clients, services, jobs, recurring,
      payments, expenses) is no longer hard-coded into RLS. It is read from
      role_permissions, which the Admin edits. Admin always passes
      has_capability() so a firm can never lock itself out of its own data.
   3. Missing rows fall back to permission_defaults(), which reproduces the
      behaviour the app had before this migration, so a firm that never opens
      the matrix behaves exactly as it does today.
   4. Admin is deliberately not editable and Payments cannot be deleted: money
      is corrected by reverse/cancel RPCs, never by removing a row. Clients,
      Services, Jobs and Expenses may be deleted, and the existing ON DELETE
      RESTRICT foreign keys already refuse to delete anything that has
      financial history.
   Paste-safe: no line comments and no blank lines, because the Supabase SQL
   editor strips newlines and would otherwise swallow the rest of the script.
   ========================================================================== */
drop policy if exists "roles read" on public.user_roles;
drop policy if exists "roles manage ins" on public.user_roles;
drop policy if exists "roles manage del" on public.user_roles;
drop policy if exists "firm isolation" on public.user_roles;
/* has_role takes app_role as an argument, so the enum swap below cannot proceed
   until every policy that calls it has gone. These three are recreated further
   down against has_capability instead. */
drop policy if exists "clients read" on public.clients;
drop policy if exists "cs read" on public.client_services;
drop policy if exists "jobs read" on public.jobs;
/* Everything that names app_role in its signature or columns has to go before
   the type can be replaced. All of it is recreated and reseeded further down, so
   this also makes the script re-runnable; the cost is that a second run resets
   an Admin's permission choices back to the defaults. */
drop function if exists public.has_role(uuid, public.app_role);
drop function if exists public.my_roles();
drop function if exists public.permission_matrix();
drop function if exists public.set_role_permission(public.app_role, text, boolean, boolean, boolean, boolean, boolean);
drop function if exists public.permission_defaults(public.app_role, text);
drop function if exists public.effective_permissions(uuid, public.app_role, text);
drop function if exists public.ensure_role_permission(uuid, public.app_role, text);
drop table if exists public.role_permissions;
alter table public.firm_invites alter column role drop default;
alter table public.user_roles alter column role drop default;
create type public.app_role_v2 as enum ('admin','staff','cashier');
alter table public.user_roles alter column role type public.app_role_v2 using (case role::text when 'owner' then 'admin' when 'admin' then 'admin' when 'staff' then 'staff' else 'cashier' end)::public.app_role_v2;
alter table public.firm_invites alter column role type public.app_role_v2 using (case role::text when 'owner' then 'admin' when 'admin' then 'admin' when 'staff' then 'staff' else 'cashier' end)::public.app_role_v2;
alter table public.firm_invites alter column role set default 'staff';
alter table public.user_roles alter column role set default 'staff';
drop type public.app_role;
alter type public.app_role_v2 rename to app_role;
create or replace function public.has_role(_user_id uuid, _role public.app_role) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_roles where user_id=_user_id and role=_role) $$;
create or replace function public.is_manager() returns boolean language sql stable security definer set search_path=public as $$ select public.is_super_admin() or exists(select 1 from public.user_roles where user_id=auth.uid() and role='admin') $$;
create or replace function public.is_finance() returns boolean language sql stable security definer set search_path=public as $$ select public.is_manager() $$;
create or replace function public.is_staff_plus() returns boolean language sql stable security definer set search_path=public as $$ select public.is_super_admin() or exists(select 1 from public.user_roles where user_id=auth.uid() and role in ('admin','staff')) $$;
create or replace function public.is_cashier() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_roles where user_id=auth.uid() and role='cashier') $$;
create or replace function public.my_roles() returns setof public.app_role language sql stable security definer set search_path=public as $$ select 'admin'::public.app_role where public.is_super_admin() union select role from public.user_roles where user_id=auth.uid() and not public.is_super_admin() $$;
create policy "roles read" on public.user_roles for select to authenticated using (user_id = auth.uid() or public.is_manager());
create policy "roles manage ins" on public.user_roles for insert to authenticated with check (public.is_manager());
create policy "roles manage del" on public.user_roles for delete to authenticated using (public.is_manager());
create policy "firm isolation" on public.user_roles as restrictive for all to authenticated using (user_id=auth.uid() or exists(select 1 from public.profiles p where p.id=user_roles.user_id and p.firm_id=public.current_firm_id())) with check (exists(select 1 from public.profiles p where p.id=user_roles.user_id and p.firm_id=public.current_firm_id()));
create table if not exists public.role_permissions (firm_id uuid not null default public.current_firm_id() references public.firms(id) on delete cascade, role public.app_role not null, module text not null check (module in ('clients','services','jobs','recurring','payments','expenses')), can_view boolean not null default false, can_create boolean not null default false, can_edit boolean not null default false, can_delete boolean not null default false, can_amounts boolean not null default false, updated_by uuid default auth.uid(), updated_at timestamptz not null default now(), primary key (firm_id, role, module));
create index if not exists role_permissions_firm_idx on public.role_permissions(firm_id);
alter table public.role_permissions enable row level security;
drop policy if exists "role_permissions read" on public.role_permissions;
drop policy if exists "role_permissions firm isolation" on public.role_permissions;
create policy "role_permissions read" on public.role_permissions for select to authenticated using (firm_id=public.current_firm_id());
create policy "role_permissions firm isolation" on public.role_permissions as restrictive for all to authenticated using (firm_id=public.current_firm_id()) with check (firm_id=public.current_firm_id());
/* Defaults reproduce the pre-migration behaviour: Admin everything, Staff read the practice modules and progress job status, Cashier records payments. Admin can delete every module except Payments, because payment rows are reversed rather than removed. */
/* Payments are never deletable for anyone: set_role_permission refuses the grant and the table has no DELETE grant. Admin still deletes Clients, Services, Jobs, Recurring and Expenses, whose ON DELETE RESTRICT foreign keys are what refuse a record with financial history. */
create or replace function public.permission_defaults(_role public.app_role, _module text) returns table(can_view boolean, can_create boolean, can_edit boolean, can_delete boolean, can_amounts boolean) language sql immutable as $$ select case when _role='admin' then true when _role='cashier' then _module='payments' else true end, case when _role='admin' then true when _role='cashier' then _module='payments' else false end, case when _role='admin' then true when _role='staff' then _module='jobs' else false end, case when _role='admin' then _module<>'payments' else false end, case when _role='admin' then true when _role='cashier' then _module='payments' else false end $$;
/* can_delete is forced false for payments here as well as in set_role_permission, so a row written by any other path still cannot make has_capability('payments','delete') true. The rule is enforced at the point of use, not only at the point of writing. */
create or replace function public.effective_permissions(_firm_id uuid, _role public.app_role, _module text) returns table(can_view boolean, can_create boolean, can_edit boolean, can_delete boolean, can_amounts boolean) language sql stable security definer set search_path=public as $$ select coalesce(rp.can_view, d.can_view), coalesce(rp.can_create, d.can_create), coalesce(rp.can_edit, d.can_edit), case when _module='payments' then false else coalesce(rp.can_delete, d.can_delete) end, coalesce(rp.can_amounts, d.can_amounts) from public.permission_defaults(_role, _module) d left join public.role_permissions rp on rp.firm_id=_firm_id and rp.role=_role and rp.module=_module $$;
create or replace function public.has_capability(_module text, _action text) returns boolean language sql stable security definer set search_path=public as $$ select public.is_manager() or exists (select 1 from public.my_roles() rr cross join lateral public.effective_permissions(public.current_firm_id(), rr, _module) p where case _action when 'view' then p.can_view when 'create' then p.can_create when 'edit' then p.can_edit when 'delete' then p.can_delete when 'amounts' then p.can_amounts else false end) $$;
create or replace function public.seed_role_permissions(_firm_id uuid) returns void language plpgsql security definer set search_path=public as $$ begin insert into public.role_permissions(firm_id, role, module, can_view, can_create, can_edit, can_delete, can_amounts) select _firm_id, r.role, m.module, d.can_view, d.can_create, d.can_edit, d.can_delete, d.can_amounts from unnest(array['admin','staff','cashier']::public.app_role[]) r(role) cross join unnest(array['clients','services','jobs','recurring','payments','expenses']) m(module) cross join lateral public.permission_defaults(r.role, m.module) d on conflict (firm_id, role, module) do nothing; end $$;
select public.seed_role_permissions(id) from public.firms;
/* Returns the stored row for a role+module, creating it from the defaults if it is missing, so that an Admin editing one cell always writes a complete row. */
create or replace function public.ensure_role_permission(_firm_id uuid, _role public.app_role, _module text) returns void language plpgsql security definer set search_path=public as $$ begin insert into public.role_permissions(firm_id, role, module, can_view, can_create, can_edit, can_delete, can_amounts) select _firm_id, _role, _module, d.can_view, d.can_create, d.can_edit, d.can_delete, d.can_amounts from public.permission_defaults(_role, _module) d on conflict (firm_id, role, module) do nothing; end $$;
create or replace function public.permission_matrix() returns table(role public.app_role, module text, can_view boolean, can_create boolean, can_edit boolean, can_delete boolean, can_amounts boolean, editable boolean) language plpgsql security definer set search_path=public as $$ begin if not public.is_manager() then raise exception 'Not authorised'; end if; return query select r.role, m.module, coalesce(rp.can_view, d.can_view), coalesce(rp.can_create, d.can_create), coalesce(rp.can_edit, d.can_edit), case when m.module='payments' then false else coalesce(rp.can_delete, d.can_delete) end, coalesce(rp.can_amounts, d.can_amounts), r.role <> 'admin' from unnest(array['admin','staff','cashier']::public.app_role[]) r(role) cross join unnest(array['clients','services','jobs','recurring','payments','expenses']) m(module) cross join lateral public.permission_defaults(r.role, m.module) d left join public.role_permissions rp on rp.firm_id=public.current_firm_id() and rp.role=r.role and rp.module=m.module; end $$;
create or replace function public.set_role_permission(_role public.app_role, _module text, _view boolean, _create boolean, _edit boolean, _delete boolean, _amounts boolean) returns void language plpgsql security definer set search_path=public as $$ begin if not public.is_manager() then raise exception 'Not authorised'; end if; if _role = 'admin' then raise exception 'The Admin role always has full access and cannot be restricted.'; end if; if _module not in ('clients','services','jobs','recurring','payments','expenses') then raise exception 'Unknown module'; end if; if _delete and _module = 'payments' then raise exception 'Payment records are never deleted. Reverse the payment instead.'; end if; insert into public.role_permissions(firm_id, role, module, can_view, can_create, can_edit, can_delete, can_amounts) values (public.current_firm_id(), _role, _module, coalesce(_view,false), coalesce(_view,false) and coalesce(_create,false), coalesce(_view,false) and coalesce(_edit,false), coalesce(_view,false) and coalesce(_delete,false), coalesce(_view,false) and coalesce(_amounts,false)) on conflict (firm_id, role, module) do update set can_view=excluded.can_view, can_create=excluded.can_create, can_edit=excluded.can_edit, can_delete=excluded.can_delete, can_amounts=excluded.can_amounts, updated_by=auth.uid(), updated_at=now(); insert into public.audit_logs(user_id, action, module, record_id, new_value) values (auth.uid(), 'role_permission_changed', 'role_permissions', _role::text || ':' || _module, jsonb_build_object('view', coalesce(_view,false), 'create', coalesce(_view,false) and coalesce(_create,false), 'edit', coalesce(_view,false) and coalesce(_edit,false), 'delete', coalesce(_view,false) and coalesce(_delete,false), 'amounts', coalesce(_view,false) and coalesce(_amounts,false))); end $$;
/* Aggregates are computed in the inner grouped query and only assembled into jsonb outside it, because an aggregate may not contain another aggregate. my_roles() is cross joined rather than referenced in the select list so that a user holding several roles gets the union of their grants. */
create or replace function public.my_permissions() returns jsonb language sql stable security definer set search_path=public as $$ select coalesce(jsonb_object_agg(s.module, jsonb_build_object('view', s.can_view, 'create', s.can_create, 'edit', s.can_edit, 'delete', s.can_delete, 'amounts', s.can_amounts)), '{}'::jsonb) from (select m.module, bool_or(p.can_view) as can_view, bool_or(p.can_create) as can_create, bool_or(p.can_edit) as can_edit, bool_or(p.can_delete) as can_delete, bool_or(p.can_amounts) as can_amounts from unnest(array['clients','services','jobs','recurring','payments','expenses']) m(module) cross join public.my_roles() rr cross join lateral public.effective_permissions(public.current_firm_id(), rr, m.module) p group by m.module) s $$;
create or replace function public.reset_role_permissions() returns void language plpgsql security definer set search_path=public as $$ begin if not public.is_manager() then raise exception 'Not authorised'; end if; delete from public.role_permissions where firm_id=public.current_firm_id(); perform public.seed_role_permissions(public.current_firm_id()); insert into public.audit_logs(user_id, action, module, record_id, reason) values (auth.uid(), 'role_permissions_reset', 'role_permissions', public.current_firm_id()::text, 'restored defaults'); end $$;
/* RLS now reads the matrix instead of hard-coded roles. A grant is firm-wide: once Staff can see Clients they see every client, not only assigned ones. */
drop policy if exists "clients read" on public.clients;
drop policy if exists "clients ins" on public.clients;
drop policy if exists "clients upd" on public.clients;
drop policy if exists "clients del" on public.clients;
create policy "clients read" on public.clients for select to authenticated using (public.has_capability('clients','view'));
create policy "clients ins" on public.clients for insert to authenticated with check (public.has_capability('clients','create'));
create policy "clients upd" on public.clients for update to authenticated using (public.has_capability('clients','edit')) with check (public.has_capability('clients','edit'));
create policy "clients del" on public.clients for delete to authenticated using (public.has_capability('clients','delete'));
drop policy if exists "services read" on public.services;
drop policy if exists "services ins" on public.services;
drop policy if exists "services upd" on public.services;
drop policy if exists "services del" on public.services;
create policy "services read" on public.services for select to authenticated using (public.has_capability('services','view'));
create policy "services ins" on public.services for insert to authenticated with check (public.has_capability('services','create'));
create policy "services upd" on public.services for update to authenticated using (public.has_capability('services','edit')) with check (public.has_capability('services','edit'));
create policy "services del" on public.services for delete to authenticated using (public.has_capability('services','delete'));
/* client_services carries the retainer schedule, so it answers to either the Recurring module (the /recurring page) or the Clients module (the client detail page). Either grant is enough. */
drop policy if exists "cs read" on public.client_services;
drop policy if exists "cs ins" on public.client_services;
drop policy if exists "cs upd" on public.client_services;
drop policy if exists "cs del" on public.client_services;
create policy "cs read" on public.client_services for select to authenticated using (public.has_capability('recurring','view') or public.has_capability('clients','view'));
create policy "cs ins" on public.client_services for insert to authenticated with check (public.has_capability('recurring','create') or public.has_capability('clients','create'));
create policy "cs upd" on public.client_services for update to authenticated using (public.has_capability('recurring','edit') or public.has_capability('clients','edit')) with check (public.has_capability('recurring','edit') or public.has_capability('clients','edit'));
create policy "cs del" on public.client_services for delete to authenticated using (public.has_capability('recurring','delete'));
drop policy if exists "jobs read" on public.jobs;
drop policy if exists "jobs ins" on public.jobs;
drop policy if exists "jobs upd" on public.jobs;
drop policy if exists "jobs del" on public.jobs;
create policy "jobs read" on public.jobs for select to authenticated using (public.has_capability('jobs','view'));
create policy "jobs ins" on public.jobs for insert to authenticated with check (public.has_capability('jobs','create'));
create policy "jobs upd" on public.jobs for update to authenticated using (public.has_capability('jobs','edit')) with check (public.has_capability('jobs','edit'));
create policy "jobs del" on public.jobs for delete to authenticated using (public.has_capability('jobs','delete'));
/* Colleague names are needed to render "Assigned to" on any list the caller can already read, so profiles read follows module access rather than a fixed role list. */
drop policy if exists "profiles read" on public.profiles;
create policy "profiles read" on public.profiles for select to authenticated using (id = auth.uid() or public.has_capability('clients','view') or public.has_capability('jobs','view') or public.is_manager());
/* Payments deliberately have no update policy: allocated_amount and status are moved by allocate_payment / reverse_payment so the totals stay correct. The Payments Edit column therefore gates reversal. */
drop policy if exists "pay read" on public.payments;
drop policy if exists "pay ins" on public.payments;
drop policy if exists "alloc read" on public.payment_allocations;
drop policy if exists "rev read" on public.payment_reversals;
create policy "pay read" on public.payments for select to authenticated using (public.has_capability('payments','view'));
create policy "pay ins" on public.payments for insert to authenticated with check (public.has_capability('payments','create') and created_by=auth.uid());
create policy "alloc read" on public.payment_allocations for select to authenticated using (public.has_capability('payments','edit'));
create policy "rev read" on public.payment_reversals for select to authenticated using (public.has_capability('payments','edit'));
/* The expenses / recurring_payments tables arrive with the job-payment workflow migration, which is not on every database yet. Policies cannot be created against a missing relation, so these are applied only when the table is present; the matrix still lists Expenses as a module and it starts working the moment that migration lands. */
do $$ begin if to_regclass('public.expenses') is not null then drop policy if exists "expenses read" on public.expenses; drop policy if exists "expenses write" on public.expenses; drop policy if exists "expenses ins" on public.expenses; drop policy if exists "expenses upd" on public.expenses; create policy "expenses read" on public.expenses for select to authenticated using (public.has_capability('expenses','view')); create policy "expenses ins" on public.expenses for insert to authenticated with check (public.has_capability('expenses','create')); create policy "expenses upd" on public.expenses for update to authenticated using (public.has_capability('expenses','edit')) with check (public.has_capability('expenses','edit')); end if; if to_regclass('public.recurring_payments') is not null then drop policy if exists "recurring_payments read" on public.recurring_payments; drop policy if exists "recurring_payments write" on public.recurring_payments; drop policy if exists "recurring_payments ins" on public.recurring_payments; drop policy if exists "recurring_payments upd" on public.recurring_payments; drop policy if exists "recurring_payments del" on public.recurring_payments; create policy "recurring_payments read" on public.recurring_payments for select to authenticated using (public.has_capability('recurring','view')); create policy "recurring_payments ins" on public.recurring_payments for insert to authenticated with check (public.has_capability('recurring','create')); create policy "recurring_payments upd" on public.recurring_payments for update to authenticated using (public.has_capability('recurring','edit')) with check (public.has_capability('recurring','edit')); create policy "recurring_payments del" on public.recurring_payments for delete to authenticated using (public.has_capability('recurring','delete')); end if; end $$;
/* RLS filters rows, not columns, so a Cashier who may view payments would still receive every amount over PostgREST if the UI read the table directly. These two list RPCs blank the money columns server-side unless the caller holds the module's amounts grant, so the figure genuinely never reaches the browser. */
/* These six are SECURITY DEFINER, which bypasses RLS, so each one must repeat the
   firm filter and the view grant itself. Without the firm_id predicate they would
   return every firm's rows, and has_capability() inside them would still resolve
   against the CALLER's firm, so the money columns would be unmasked for another
   firm's data. */
create or replace function public.payments_list() returns table(id uuid, payment_code text, client_id uuid, job_id uuid, amount numeric, mode text, payment_date date, reference text, narration text, status text, created_at timestamptz) language sql stable security definer set search_path=public as $$ select p.id, p.payment_code, p.client_id, p.job_id, case when public.has_capability('payments','amounts') then p.amount end, p.mode, p.payment_date, p.reference, p.narration, p.status, p.created_at from public.payments p where p.firm_id=public.current_firm_id() and public.has_capability('payments','view') order by p.created_at desc $$;
create or replace function public.jobs_list() returns table(id uuid, job_code text, client_id uuid, client_name text, service_id uuid, service_name text, client_service_id uuid, title text, period_start date, period_end date, fee numeric, discount numeric, net_amount numeric, due_date date, assigned_staff uuid, assigned_staff_name text, status text, financial_status text, notes text, auto_invoice boolean, created_at timestamptz, invoice_id uuid, invoice_no text, invoice_status text) language sql stable security definer set search_path=public as $$ select j.id, j.job_code, j.client_id, c.name, j.service_id, s.name, j.client_service_id, j.title, j.period_start, j.period_end, case when public.has_capability('jobs','amounts') then j.fee end, case when public.has_capability('jobs','amounts') then j.discount end, case when public.has_capability('jobs','amounts') then j.net_amount end, j.due_date, j.assigned_staff, pf.full_name, j.status, j.financial_status, j.notes, j.auto_invoice, j.created_at, inv.id, inv.invoice_no, inv.status from public.jobs j left join public.clients c on c.id=j.client_id left join public.services s on s.id=j.service_id left join public.profiles pf on pf.id=j.assigned_staff left join lateral (select i.id, i.invoice_no, i.status from public.invoice_items ii join public.invoices i on i.id=ii.invoice_id where ii.job_id=j.id and i.status<>'cancelled' order by i.created_at desc limit 1) inv on true where j.firm_id=public.current_firm_id() and public.has_capability('jobs','view') order by j.due_date asc nulls last $$;
create or replace function public.recurring_list() returns table(id uuid, client_id uuid, client_name text, service_id uuid, service_name text, agreed_fee numeric, frequency text, start_date date, end_date date, due_days int, assigned_staff uuid, assigned_staff_name text, status text, notes text, auto_invoice boolean, created_at timestamptz) language sql stable security definer set search_path=public as $$ select cs.id, cs.client_id, c.name, cs.service_id, s.name, case when public.has_capability('recurring','amounts') then cs.agreed_fee end, cs.frequency, cs.start_date, cs.end_date, cs.due_days, cs.assigned_staff, pf.full_name, cs.status, cs.notes, cs.auto_invoice, cs.created_at from public.client_services cs left join public.clients c on c.id=cs.client_id left join public.services s on s.id=cs.service_id left join public.profiles pf on pf.id=cs.assigned_staff where cs.firm_id=public.current_firm_id() and public.has_capability('recurring','view') order by cs.created_at $$;
create or replace function public.client_services_list(_client_id uuid) returns table(id uuid, client_id uuid, service_id uuid, service_name text, service_type text, auto_invoice boolean, agreed_fee numeric, frequency text, start_date date, end_date date, due_days int, assigned_staff uuid, assigned_staff_name text, status text, notes text, created_at timestamptz) language sql stable security definer set search_path=public as $$ select cs.id, cs.client_id, cs.service_id, s.name, s.service_type, s.auto_invoice, case when public.has_capability('recurring','amounts') or public.has_capability('services','amounts') then cs.agreed_fee end, cs.frequency, cs.start_date, cs.end_date, cs.due_days, cs.assigned_staff, pf.full_name, cs.status, cs.notes, cs.created_at from public.client_services cs left join public.services s on s.id=cs.service_id left join public.profiles pf on pf.id=cs.assigned_staff where cs.client_id=_client_id and cs.firm_id=public.current_firm_id() and (public.has_capability('recurring','view') or public.has_capability('clients','view')) order by cs.created_at $$;
create or replace function public.client_jobs_list(_client_id uuid) returns table(id uuid, job_code text, client_id uuid, service_id uuid, service_name text, title text, period_start date, period_end date, fee numeric, discount numeric, net_amount numeric, due_date date, assigned_staff uuid, assigned_staff_name text, status text, financial_status text, notes text, auto_invoice boolean, created_at timestamptz, invoice_id uuid, invoice_no text, invoice_status text) language sql stable security definer set search_path=public as $$ select j.id, j.job_code, j.client_id, j.service_id, s.name, j.title, j.period_start, j.period_end, case when public.has_capability('jobs','amounts') then j.fee end, case when public.has_capability('jobs','amounts') then j.discount end, case when public.has_capability('jobs','amounts') then j.net_amount end, j.due_date, j.assigned_staff, pf.full_name, j.status, j.financial_status, j.notes, j.auto_invoice, j.created_at, inv.id, inv.invoice_no, inv.status from public.jobs j left join public.services s on s.id=j.service_id left join public.profiles pf on pf.id=j.assigned_staff left join lateral (select i.id, i.invoice_no, i.status from public.invoice_items ii join public.invoices i on i.id=ii.invoice_id where ii.job_id=j.id and i.status<>'cancelled' order by i.created_at desc limit 1) inv on true where j.client_id=_client_id and j.firm_id=public.current_firm_id() and public.has_capability('jobs','view') order by j.created_at desc $$;
create or replace function public.client_payments_list(_client_id uuid) returns table(id uuid, payment_code text, client_id uuid, job_id uuid, amount numeric, allocated_amount numeric, mode text, payment_date date, reference text, narration text, status text, created_at timestamptz) language sql stable security definer set search_path=public as $$ select p.id, p.payment_code, p.client_id, p.job_id, case when public.has_capability('payments','amounts') then p.amount end, case when public.has_capability('payments','amounts') then p.allocated_amount end, p.mode, p.payment_date, p.reference, p.narration, p.status, p.created_at from public.payments p where p.client_id=_client_id and p.firm_id=public.current_firm_id() and public.has_capability('payments','view') order by p.payment_date desc $$;
create or replace function public.client_lookup() returns table(id uuid, client_code text, name text) language sql stable security definer set search_path=public as $$ select id, client_code, name from public.clients where status='active' and firm_id=public.current_firm_id() and (public.has_capability('clients','view') or public.has_capability('payments','create')) order by name $$;
create or replace function public.update_job_status(_job_id uuid, _status text, _reason text) returns void language plpgsql security definer set search_path=public as $$ begin perform public.firm_guard('jobs', _job_id); if not public.has_capability('jobs','edit') then raise exception 'Not authorised'; end if; perform set_config('app.status_reason', coalesce(_reason,''), true); update public.jobs set status=_status where id=_job_id; end $$;
create or replace function public.generate_recurring_jobs(_upto date) returns integer language plpgsql security definer set search_path=public as $$ declare cs record; ps date; pe date; step interval; n int := 0; svc record; lbl text; begin if not public.has_capability('recurring','edit') then raise exception 'Not authorised'; end if; for cs in select * from public.client_services where status='active' and firm_id=public.current_firm_id() loop select * into svc from public.services where id=cs.service_id; if cs.frequency='one_time' then insert into public.jobs(client_id, service_id, client_service_id, title, period_start, period_end, fee, due_date, assigned_staff, created_by) values (cs.client_id, cs.service_id, cs.id, svc.name, cs.start_date, cs.start_date, cs.agreed_fee, cs.start_date + cs.due_days, cs.assigned_staff, auth.uid()) on conflict do nothing; if found then n := n + 1; end if; continue; end if; step := case cs.frequency when 'monthly' then interval '1 month' when 'quarterly' then interval '3 months' when 'half_yearly' then interval '6 months' else interval '1 year' end; ps := date_trunc('month', cs.start_date)::date; while ps <= _upto and (cs.end_date is null or ps <= cs.end_date) loop pe := (ps + step - interval '1 day')::date; lbl := case cs.frequency when 'monthly' then to_char(ps,'Mon YYYY') when 'yearly' then 'FY ' || to_char(ps,'YYYY') else to_char(ps,'Mon YYYY') || ' – ' || to_char(pe,'Mon YYYY') end; insert into public.jobs(client_id, service_id, client_service_id, title, period_start, period_end, fee, due_date, assigned_staff, created_by) values (cs.client_id, cs.service_id, cs.id, svc.name || ' – ' || lbl, ps, pe, cs.agreed_fee, pe + cs.due_days, cs.assigned_staff, auth.uid()) on conflict do nothing; if found then n := n + 1; end if; ps := (ps + step)::date; end loop; end loop; return n; end $$;
create or replace function public.reverse_payment(_payment_id uuid, _reason text) returns void language plpgsql security definer set search_path=public as $$ declare r record; begin if not public.has_capability('payments','edit') then raise exception 'Not authorised'; end if; perform public.firm_guard('payments', _payment_id); if coalesce(trim(_reason),'') = '' then raise exception 'Reason is required'; end if; if exists(select 1 from public.payments where id=_payment_id and status='reversed') then raise exception 'Already reversed'; end if; update public.payments set status='reversed' where id=_payment_id; for r in select id from public.payment_allocations where payment_id=_payment_id and not reversed loop update public.payment_allocations set reversed=true, reversed_at=now() where id=r.id; end loop; insert into public.payment_reversals(payment_id, reason, reversed_by) values (_payment_id, _reason, auth.uid()); perform public.recalc_payment(_payment_id); end $$;
create or replace function public.reverse_allocation(_allocation_id uuid, _reason text) returns void language plpgsql security definer set search_path=public as $$ begin if not public.has_capability('payments','edit') then raise exception 'Not authorised'; end if; perform public.firm_guard('payment_allocations', _allocation_id); update public.payment_allocations set reversed=true, reversed_at=now() where id=_allocation_id and not reversed; insert into public.audit_logs(user_id, action, module, record_id, reason) values (auth.uid(),'allocation_reversed','payment_allocations',_allocation_id::text,_reason); end $$;
do $$ begin if to_regclass('public.expenses') is not null then execute $f$ create or replace function public.delete_expense(_expense_id uuid, _reason text) returns void language plpgsql security definer set search_path=public as $b$ begin if not public.has_capability('expenses','delete') then raise exception 'Not authorised'; end if; if coalesce(btrim(_reason),'')='' then raise exception 'Reason is required'; end if; perform public.firm_guard('expenses', _expense_id); delete from public.expenses where id=_expense_id; insert into public.audit_logs(user_id, action, module, record_id, reason) values (auth.uid(),'expense_deleted','expenses',_expense_id::text,_reason); end $b$ $f$; end if; end $$;
create or replace function public.create_firm(_name text, _owner_email text, _phone text, _city text, _logo_url text) returns uuid language plpgsql security definer set search_path=public as $$ declare fid uuid; begin if not public.is_super_admin() then raise exception 'Not authorised'; end if; if coalesce(trim(_name),'')='' then raise exception 'Firm name is required'; end if; insert into public.firms(name, owner_email, phone, city, logo_url) values (trim(_name), lower(trim(_owner_email)), _phone, _city, _logo_url) returning id into fid; insert into public.settings(firm_id, firm_name, phone, email) values (fid, trim(_name), _phone, lower(trim(_owner_email))); perform public.seed_role_permissions(fid); return fid; end $$;
grant delete on public.clients, public.services, public.jobs, public.client_services to authenticated;
do $$ begin if to_regclass('public.recurring_payments') is not null then execute 'grant delete on public.recurring_payments to authenticated'; end if; end $$;
do $$ begin if to_regclass('public.expenses') is not null then execute 'revoke delete on public.expenses from authenticated'; end if; if to_regclass('public.job_clearing') is not null then execute 'revoke delete on public.job_clearing from authenticated'; end if; end $$;
revoke delete on public.payments, public.invoices, public.invoice_items, public.discounts, public.payment_allocations, public.payment_reversals from authenticated;
revoke execute on function public.permission_defaults(public.app_role, text), public.effective_permissions(uuid, public.app_role, text), public.seed_role_permissions(uuid) from public, anon;
grant all on public.role_permissions to service_role;
/* has_capability must stay executable for authenticated: RLS policy expressions are evaluated with the querying user's privileges, so revoking it would make every module error out rather than merely stay locked. */
grant execute on function public.payments_list(), public.jobs_list(), public.recurring_list(), public.client_services_list(uuid), public.client_jobs_list(uuid), public.client_payments_list(uuid), public.has_capability(text, text), public.my_permissions(), public.permission_matrix(), public.set_role_permission(public.app_role, text, boolean, boolean, boolean, boolean, boolean), public.reset_role_permissions(), public.has_role(uuid, public.app_role), public.my_roles(), public.client_lookup(), public.update_job_status(uuid, text, text), public.generate_recurring_jobs(date), public.reverse_payment(uuid, text), public.reverse_allocation(uuid, text) to authenticated;
do $$ begin if to_regclass('public.expenses') is not null then execute 'grant execute on function public.delete_expense(uuid, text) to authenticated'; end if; end $$;